version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "4000:4000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - server
    networks:
      - devnet

  server:
    build: ./server
    ports:
      - "4001:4001"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - client
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
